### ISSUE TITLE
section with ID of main

### ISSUE THREAD

**Issue by indifferentghost** [mightykrakyn/LeonBingo#1]
Why do you have a `<section>` with an id of 'main' when a `<main>` tag exists?

https://github.com/mightykrakyn/LeonBingo/blob/1e5faac499e9f8b27f4abdd319b29f1b2f4dd919/views/index.html#L12

**Comment by jamescrosslin** [comment]
Building while learning while also on live stream is tough! Thank you for raising the issue. I agree, and it is fixed!
