### ISSUE TITLE
Gutters probably don't need ids

### ISSUE THREAD

**Issue by indifferentghost** [mightykrakyn/LeonBingo#2]
Considering you have two gutters that are verbaitum the same styles you can probably just have a `.gutter` class for these instead of unique Ids.

https://github.com/mightykrakyn/LeonBingo/blob/1e5faac499e9f8b27f4abdd319b29f1b2f4dd919/css/styles.css#L27-L28

**Comment by jamescrosslin** [comment]
I agree! The change has been made.
